# Site settings
title: randonom
htmltitle: Sean Glover's blog
email: seglo@randonom.com
description: > # this means to ignore newlines until "baseurl:"
  Sean Glover's blog
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: /blog/:year/:month/:title/
url: "http://seanglover.com" # the base hostname & protocol for your site

twitter_username: randonom
github_username: seglo
linkedin_username: seanaglover


# Build settings
markdown: kramdown

comments: true
