# Site settings
title: Sean Glover
htmltitle: Sean Glover | Software Engineer | Toronto
email: seglo@randonom.com
description: >
  Scala Architect, Data Engineer, OSS Author, Tech Community Organizer
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: /blog/:year/:month/:title/
url: "http://seanglover.com" # the base hostname & protocol for your site

twitter_username: seg1o
github_username: seglo
linkedin_username: seanaglover

# Build settings
markdown: kramdown

comments: true
